# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageName: 'movie-catalog-service'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: $(imageName)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'    
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'AWS'
        regionName: 'us-east-1'
        imageSource: 'imagename'
        sourceImageName: $(imageName)
        repositoryName: $(imageName)
        autoCreateRepository: true